### ISSUE TITLE
Apriltag image 

### ISSUE THREAD

**Issue by fasogbon** [stytim/k4a-calibration#3]
Please can you provide the png or pdf file of apriltag used in your example? That correspond to the tag size used in your extrinsic calibration code. Thank you

**Comment by stytim** [comment]
I am using tagStandard41h12, id=0, which is this one: [Google Drive link](https://drive.google.com/file/d/1E1c_CbFc-QRuFOdClKJYLcvgTLRL0GKZ/view?usp=sharing). After you print the AprilTag, you can measure the tag length according to [this guide](https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide) and set it here: [https://github.com/stytim/k4a-calibration/blob/master/src/camera_extrinsics.cpp#L137](https://github.com/stytim/k4a-calibration/blob/ae4f9c01dea4be5dad79ee12a45eae0e12296041/src/camera_extrinsics.cpp#L137)

**Comment by fasogbon** [comment]
Thank you for your quick reply! One more question, can we have multiple of those apriltag in the scene? I saw that you have it pasted all around the cube object in your snapshot result

**Comment by stytim** [comment]
The answer is yes. However, you need to calibrate the markers in the scene, meaning you need to know the transformation between each of the markers, so that the markers form into one big group. For the cube object in my snapshot, I know the length of my cube and I define the center of the cube as my marker coordinate system origin. You can refer to these commented lines for more info: [https://github.com/stytim/k4a-calibration/blob/master/src/camera_extrinsics.cpp#L167](https://github.com/stytim/k4a-calibration/blob/ae4f9c01dea4be5dad79ee12a45eae0e12296041/src/camera_extrinsics.cpp#L167)

**Comment by fasogbon** [comment]
Thank you a lot
